# Generated by Django 5.0.3 on 2024-04-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=254)),
                ('city_name', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=9)),
            ],
        ),
    ]
