# Generated by Django 5.0.3 on 2024-04-03 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_latitude_alter_event_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id']},
        ),
    ]
