---
name: Inspections

on:
    push:
      branches: [master]
    workflow_dispatch:

jobs:
    test-lint:
      name: Test Only
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Test
          run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
        # - name: Lint
        #   run: docker-compose run --rm app sh -c "flake8"